// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6f4ejuvj5vF5gw4NhXJ2GtPJSzdWE8kw',
    appId: '1:706286641509:web:9ba251972b488ad582018c',
    messagingSenderId: '706286641509',
    projectId: 'ihsanapp-e2d2d',
    authDomain: 'ihsanapp-e2d2d.firebaseapp.com',
    storageBucket: 'ihsanapp-e2d2d.firebasestorage.app',
    measurementId: 'G-GF71EXG990',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU8L0TyR1jAOP4CnVLPupdKzJiTQ_PkBQ',
    appId: '1:706286641509:android:9b3a11b7341f6dc382018c',
    messagingSenderId: '706286641509',
    projectId: 'ihsanapp-e2d2d',
    storageBucket: 'ihsanapp-e2d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzAbH4xCSfm0R0UXNp5rb24br2wWgSSTo',
    appId: '1:706286641509:ios:7528a8cd391d297282018c',
    messagingSenderId: '706286641509',
    projectId: 'ihsanapp-e2d2d',
    storageBucket: 'ihsanapp-e2d2d.firebasestorage.app',
    iosBundleId: 'com.example.ihsanAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzAbH4xCSfm0R0UXNp5rb24br2wWgSSTo',
    appId: '1:706286641509:ios:7528a8cd391d297282018c',
    messagingSenderId: '706286641509',
    projectId: 'ihsanapp-e2d2d',
    storageBucket: 'ihsanapp-e2d2d.firebasestorage.app',
    iosBundleId: 'com.example.ihsanAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6f4ejuvj5vF5gw4NhXJ2GtPJSzdWE8kw',
    appId: '1:706286641509:web:de463d0e16b936d282018c',
    messagingSenderId: '706286641509',
    projectId: 'ihsanapp-e2d2d',
    authDomain: 'ihsanapp-e2d2d.firebaseapp.com',
    storageBucket: 'ihsanapp-e2d2d.firebasestorage.app',
    measurementId: 'G-YKP4XHYHRS',
  );

}